"""add-feedbacks-table

Revision ID: 73b312d3244e
Revises: 858b066638c6
Create Date: 2026-05-11 15:06:59.950107

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73b312d3244e'
down_revision: Union[str, Sequence[str], None] = '858b066638c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'REJECTED', name='feedback_status'), nullable=False),
    sa.Column('type', sa.Enum('BUG', 'WISH', 'OTHER', name='feedback_type'), nullable=False),
    sa.Column('form_fill_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('form_fill_time_ms >= 1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_form_fill_time_ms'), 'feedbacks', ['form_fill_time_ms'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_card_reviews_card_id'), table_name='card_reviews')
    op.create_unique_constraint(None, 'card_reviews', ['card_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_reviews', type_='unique')
    op.create_index(op.f('ix_card_reviews_card_id'), 'card_reviews', ['card_id'], unique=True)
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_form_fill_time_ms'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
