"""change users and profiles tables

Revision ID: 858b066638c6
Revises: a3de1a9b7bef
Create Date: 2026-03-24 17:44:00.606616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858b066638c6'
down_revision: Union[str, Sequence[str], None] = 'a3de1a9b7bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('profiles_email_key'), 'profiles', type_='unique')
    op.create_unique_constraint(None, 'profiles', ['username'])
    op.drop_column('profiles', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.create_unique_constraint(op.f('profiles_email_key'), 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
