"""create_card_reviews_and_review_logs_tables

Revision ID: a7c93a7ef217
Revises: 598609c6553d
Create Date: 2026-03-11 14:40:09.873629

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7c93a7ef217'
down_revision: Union[str, Sequence[str], None] = '598609c6553d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_reviews',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_reviews_card_id'), 'card_reviews', ['card_id'], unique=True)
    op.create_index(op.f('ix_card_reviews_due'), 'card_reviews', ['due'], unique=False)
    op.create_table('review_logs',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['card_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_review_datetime'), 'review_logs', ['review_datetime'], unique=False)
    op.create_index(op.f('ix_review_logs_review_id'), 'review_logs', ['review_id'], unique=False)
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_index(op.f('ix_review_logs_review_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_review_datetime'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_card_reviews_due'), table_name='card_reviews')
    op.drop_index(op.f('ix_card_reviews_card_id'), table_name='card_reviews')
    op.drop_table('card_reviews')
    # ### end Alembic commands ###