from fastapi import Depends, APIRouter

from api.v1.routers.utils.dependencies import get_ml_service

from api.v1.schemas.requests.ml_requests import (
    SimilarRequest,
    WordLevelRequest,
    SentenceRequest,
    PredictRequest,
    PredictTopicRequest,
    PredictTopicsRequest,
    PreprocessRequest,
    CheckPlagiarismRequest,
    SpamClassificationRequest,
    UserSentenceRequest,
    SentenceContextRequest,
)

from api.v1.services.ml_service import MLService


ml_router = APIRouter(
    prefix="/ml/models",
    tags=["ml models"]
)


@ml_router.post(
    path="/similar",
    summary="Get similar words",
    description=(
        "Returns a list of words similar to the input array of words. "
        "The number of similar words returned is determined by the `topn` parameter."
    )
)
async def get_similar_words(
    data: SimilarRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.recieve_similar_words(data=data)


@ml_router.post(
    path="/word_level",
    summary="Get word CEFR level",
    description=(
        "Determines the CEFR level of the provided word."
    )
)
async def get_word_level(
    data: WordLevelRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.get_word_level(data=data)


@ml_router.post(
    path="/sentence",
    summary="Generate sentence",
    description=(
        "Generates a sentence using the provided word, "
        "difficulty level and language."
    )
)
async def generate_sentence(
    data: SentenceRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.generate_sentence(data=data)


@ml_router.post(
    path="/correct_paragraph",
    summary="Correct paragraph",
    description=(
        "Corrects grammar and spelling mistakes "
        "in the provided sentence."
    )
)
async def correct_paragraph(
    data: UserSentenceRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.correct_paragraph(data=data)


@ml_router.post(
    path="/sentence_level",
    summary="Get sentence level",
    description=(
        "Determines the CEFR level of the provided sentence."
    )
)
async def get_sentence_level(
    data: UserSentenceRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.get_sentence_level(data=data)


@ml_router.post(
    path="/sentence_context_level",
    summary="Get sentence context level",
    description=(
        "Determines the contextual level "
        "of a word inside a sentence."
    )
)
async def get_sentence_context_level(
    data: SentenceContextRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.get_sentence_context_level(data=data)


@ml_router.post(
    path="/sentence_context_rate",
    summary="Rate sentence context",
    description=(
        "Evaluates how correctly the word "
        "is used inside the sentence."
    )
)
async def rate_sentence_context(
    data: SentenceContextRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.rate_sentence_context(data=data)


@ml_router.post(
    path="/predict",
    summary="Predict user level",
    description=(
        "Predicts the user's language level "
        "based on learning statistics."
    )
)
async def predict_level(
    data: PredictRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.predict_level(data=data)


@ml_router.post(
    path="/predict_topic",
    summary="Predict topic",
    description=(
        "Predicts the topic of a single sentence."
    )
)
async def predict_topic(
    data: PredictTopicRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.predict_topic(data=data)


@ml_router.post(
    path="/predict_topics",
    summary="Predict topics",
    description=(
        "Predicts topics for multiple sentences."
    )
)
async def predict_topics(
    data: PredictTopicsRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.predict_topics(data=data)


@ml_router.post(
    path="/check_plagiarism",
    summary="Check AI plagiarism",
    description=(
        "Checks whether the text was generated by AI."
    )
)
async def check_plagiarism(
    data: CheckPlagiarismRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.check_plagiarism(data=data)


@ml_router.post(
    path="/spam_classification",
    summary="Classify spam",
    description=(
        "Classifies the sentence as spam or ham."
    )
)
async def classify_spam(
    data: SpamClassificationRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.classify_spam(data=data)


@ml_router.post(
    path="/preprocess",
    summary="Preprocess text",
    description=(
        "Preprocesses text for NLP tasks."
    )
)
async def preprocess_text(
    data: PreprocessRequest,
    service: MLService = Depends(get_ml_service),
):
    return await service.preprocess_text(data=data)

@ml_router.get(
    path="/health",
    summary="Health check",
    description=(
        "Sends a GET request to the https://jsonplaceholder.typicode.com/posts if the URL in config is set to default, to see if the ML service works properly."
        "Returns a simple message indicating that the service is operational."
 )
)
async def health_check(
    service: MLService = Depends(get_ml_service),
):
    return await service.test_service()