from enum import Enum


class AuthErrorCodes(Enum):
    FORBIDDEN = "FORBIDDEN"
    EMAIL_OR_PASSWORD_INCORRECT = "EMAIL_OR_PASSWORD_INCORRECT"
    INVALID_OR_EXPIRED_REFRESH_TOKEN = "INVALID_OR_EXPIRED_REFRESH_TOKEN"
    INVALID_OLD_PASSWORD = "INVALID_OLD_PASSWORD"
    NEW_PASSWORD_MUST_DIFFER = "NEW_PASSWORD_MUST_DIFFER"
