from enum import Enum


class BaseErrorCodes(Enum):
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    INVALID_PAGINATION = "INVALID_PAGINATION"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INVALID_FILTER = "INVALID_FILTER"
    INVALID_FORM_FILLED_TIME = "INVALID_FORM_FILLED_TIME"
