from enum import Enum


class DeckErrorCodes(Enum):
    DECK_NOT_FOUND = "DECK_NOT_FOUND"
    DECK_ALREADY_EXISTS = "DECK_ALREADY_EXISTS"
    INVALID_DECK_NAME = "INVALID_DECK_NAME"
    DECK_BELONGS_TO_ANOTHER_USER = "DECK_BELONGS_TO_ANOTHER_USER"
