from enum import StrEnum


class FeedbackErrorCodes(StrEnum):
    FEEDBACK_NOT_FOUND = "FEEDBACK_NOT_FOUND"
    FEEDBACK_ALREADY_PROCESSED = "FEEDBACK_ALREADY_PROCESSED"

    FEEDBACK_MESSAGE_IS_INVALID = "FEEDBACK_MESSAGE_IS_INVALID"
