from enum import Enum


class FilesErrorCodes(Enum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_DELETE_FAILED = "FILE_DELETE_FAILED"
    FILE_ACCESS_DENIED = "FILE_ACCESS_DENIED"
    FILE_BELONGS_TO_ANOTHER_USER = "FILE_BELONGS_TO_ANOTHER_USER"