from enum import Enum

class ProfilesErrorCodes(Enum):
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    USERNAME_ALREADY_IN_USE = "USERNAME_ALREADY_IN_USE"
    USERNAME_MUST_BE_BETWEEN_3_AND_50_CHARACTERS = "USERNAME_MUST_BE_BETWEEN_3_AND_50_CHARACTERS"
    BIO_MUST_BE_AT_MOST_300_CHARACTERS = "BIO_MUST_BE_AT_MOST_300_CHARACTERS"

