from enum import Enum


class QuizErrorCodes(Enum):
    IMAGE_DOES_NOT_EXIST_FOR_CARD = "IMAGE_DOES_NOT_EXIST_FOR_CARD"
    SOUND_DOES_NOT_EXIST_FOR_CARD = "SOUND_DOES_NOT_EXIST_FOR_CARD"

    AT_LEAST_ONE_INPUT_TYPE_MUST_BE_AVAILABLE = "AT_LEAST_ONE_INPUT_TYPE_MUST_BE_AVAILABLE"
    AT_LEAST_ONE_PRESENTATION_TYPE_MUST_BE_AVAILABLE = "AT_LEAST_ONE_INPUT_TYPE_MUST_BE_AVAILABLE"

    INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
    THERE_IS_NO_CARD_TO_REVIEW = "THERE_IS_NO_CARD_TO_REVIEW"

    ALL_FIELDS_ARE_EXCLUDED = "ALL_FIELDS_ARE_EXCLUDED"

    INVALID_RATING = "INVALID_RATING"
    NO_COMPATIBLE_COMBINATIONS_FOUND = "NO_COMPATIBLE_COMBINATIONS_FOUND"
